item_variables:
  - availability_in_3_months_item
  - availability_in_30_days_item
  - availability_market_item
  - availability_shop_item
  - no_availability_reason_item
  - shortage_item
  - sold_shop_item
  - availability_30_days_prior_item
  - barrier_consumer_item
  - demand_change_last_30_days_item
  - sales_past_week_item
  - imported_item
  - price_item
  - price_evolution_expectations_item
  - discount_item
  - price_30_days_prior_item
  - price_change_last_30_days_item
  - price_decrease_reason_item
  - price_in_3_months_item
  - price_increase_reason_item
  - brand_item
  - type_item
  - barrier_supply_item
  - no_stock_duration_days_item
  - recent_restock_item
  - restock_capability_item
  - restock_difficulties_item
  - restock_difficulties_reasons_item
  - restock_last_days_item
  - restock_wait_days_item
  - restock_wait_days_max_item
  - restock_wait_days_min_item
  - stock_duration_days_item
  - supplier_unique_item
  - supplier_origin_item
  - supplier_origin_country_item
  - supplier_origin_locality_item
