items:
  - egg
  - chicken_meat
  - goat_meat
  - pork_meat
  - sheep_meat
  - camel_meat
  - yogurt
  - sardines_canned
  - tuna_canned
  - tuna
  - fish_dried
  - fish_canned
  - fish_paste
  - fish_fresh
  - lamb_meat
  - beef_meat
  - honey
  - bread_subsidised
  - bread
  - dry_cells
  - blanket_heavy
  - blanket
  - pillow
  - bed_sheets
  - sleeping_mat
  - plastic_carpet
  - carpet
  - sim_card
  - internet_and_phone_call
  - phone_call_minute
  - mobile_phone 
  - internet_data_modem
  - internet_data
  - shea_butter
  - butter
  - margarine
  - sugar_cube
  - sugar_wholesale
  - sugar
  - mayonnaise
  - groundnut_oil
  - palm_oil
  - vegetable_oil
  - salt
  - chilli_dried
  - tarpaulin
  - pliers
  - nylon_sheet
  - pickaxe
  - pair_of_shears
  - burnt_brick
  - mud_brick
  - hasira
  - gravel
  - hammer
  - wooden_mingle
  - hinge
  - metal_bar_8mm
  - metal_bar_6mm
  - iron_sheet
  - roof_nails_and_washer
  - nails_38mm
  - nails_50mm
  - nails_63mm
  - nails_75mm
  - sand
  - spade
  - timber
  - vent_pipe
  - wheelbarrow
  - wooden_pole
  - wooden_saw
  - rake
  - plastic_gloves
  - rope
  - draw_hoe
  - hoe
  - concrete_hollow_block
  - shovel
  - duct_tape
  - handsaw
  - sawn_wood
  - machete
  - corrugated_iron_sheet
  - water_tank
  - wooden_swedish_door
  - sewer_pipes
  - steel_reinforcement_bar_8mm
  - steel_reinforcement_bar_14mm
  - cement
  - wooden_window
  - insulation_roll
  - drinking_water_pipe
  - roll_tie_wire
  - tent
  - bucket_with_tap
  - woven_sack
  - collapsible_jerrycan
  - small_water_container
  - jerrycan
  - tub
  - water_container
  - small_fuel_container
  - garbage_bag
  - bag_type_boro
  - plastic_bag
  - bucket
  - coffee
  - powder_milk
  - baby_milk
  - condensed_milk
  - camel_milk
  - fresh_milk
  - black_tea
  - green_tea
  - battery_type_a
  - battery_type_c
  - grass_thatch
  - fertilizer_npk_15
  - fertilizer_dap
  - fire_blanket
  - grass
  - charcoal
  - bamboo
  - firewood
  - coal
  - wood_pellet
  - kindling
  - fuel_gel
  - gas_heating
  - petrol_black_market
  - petrol_local
  - petrol_local_subsidised
  - petrol_manually_refined
  - gas_liquid_local
  - cooking_fuel_black_market
  - cooking_fuel
  - gas_liquid
  - lpg_subsidised
  - lpg
  - petrol_imported
  - petrol
  - kerosene_local
  - kerosene_manually_refined
  - kerosene_imported
  - kerosene
  - diesel_black_market
  - diesel_local 
  - diesel_imported
  - diesel_local_subsidised
  - diesel_manually_refined
  - diesel
  - electricity_for_vehicle
  - electricity_heating
  - fire_extinguisher
  - seasonal_wild_fruit
  - avocado
  - mango
  - pineapple
  - banana
  - guava
  - papaya
  - plantain
  - dates
  - watermelon
  - nectarine
  - apple
  - orange
  - bulgur
  - maize_wholesale
  - wheat_flour_imported
  - maize_grain
  - maize_flour
  - buckwheat_flour
  - oat_flakes
  - oat_flour
  - wheat_flour
  - rice_imported
  - sorghum_grain_wholesale
  - sorghum_flour
  - sorghum_grain
  - sorghum_red
  - teff
  - enset
  - barley
  - millet_flour
  - fonio
  - buckwheat
  - couscous
  - rice
  - heater
  - lock
  - mosquito_net
  - brush_and_dustpan
  - stove
  - gas_stove
  - dishwashing_soap
  - kettle
  - bowl
  - jug
  - cooking_pot_with_lid
  - cooking_pot
  - kitchen_utensils_set
  - fork
  - vacuum_flask
  - kitchen_knife
  - scouring_pad
  - knife
  - plate
  - serving_spoon
  - spoon
  - mug
  - cup
  - cleaning_sponge
  - kitchen_towel
  - pan
  - labor_unskilled
  - green_pea_split
  - lentil_split
  - lentil
  - fava_bean
  - fava_bean_canned
  - mung_bean
  - bean_canned
  - bean_wholesale
  - red_bean
  - black_bean
  - bean
  - chickpea_split
  - chickpea
  - chickpea_canned
  - cowpea
  - pigeon_pea
  - green_pea
  - voandzou
  - battery_powered_torch
  - torch
  - solar_lamp
  - lamp
  - chicken  
  - goat  
  - peanut_nut
  - peanut_full
  - groundnut
  - pistachio
  - sesame
  - toilet_paper
  - shaving_cream_men
  - shaving_cream_women
  - wet_wipes
  - body_lotion
  - insect_repellent
  - deodorant
  - nail_clipper
  - baby_oil
  - comb
  - toothbrush_child
  - toothbrush
  - toothpaste
  - reusable_sanitary_pad
  - sanitary_pad
  - towel_baby
  - towel
  - bleach
  - laundry_detergent_liquid
  - soap_box
  - laundry_soap_bar
  - laundry_detergent_powder
  - soap_liquid
  - soap
  - disposable_razor_women
  - disposable_razor
  - shampoo
  - diaper
  - pesticide
  - paracetamol
  - disinfectant
  - hand_sanitizer
  - ibuprofen
  - condom
  - vitamin_b
  - metformin
  - captopril
  - zithromax
  - pregnancy_test
  - electrolytes
  - antiseptic_iodine
  - oral_contraceptive
  - injectable_contraceptive
  - children_anti_flu_drug
  - buscopan
  - penicillin_benzathine 
  - amoxicillin
  - albendazole
  - anti_malarial_drug
  - metoclopramide
  - metronidazole
  - surface_sanitizer
  - sterile_alcohol
  - surgical_gloves
  - surgical_face_mask
  - cloth_face_mask
  - basic_face_mask
  - pasta
  - tomato_paste
  - cheese_hard
  - cereal_porridge
  - rent
  - potato
  - manioc
  - sweet_potato
  - yam
  - cassava
  - cassava_flour
  - turnip
  - sharpener
  - notebook
  - rubber
  - blackboard
  - chalk
  - school_bag
  - attendance_register
  - crayon
  - paper
  - duster
  - maps_set
  - maths_set
  - colouring_pencil
  - pen_pencil_bundle
  - pencil_case
  - pencil
  - marker
  - pen
  - ruler
  - calculator
  - scissors
  - whiteboard
  - blackboard_drawing_set
  - bag
  - eggplant
  - onion
  - pumpkin
  - tomato
  - spinach
  - leafy_green
  - carrot
  - zucchini
  - okra
  - olive
  - cucumber
  - mulukhiya
  - cabbage
  - kale
  - pepper
  - water_purification_tablet
  - water_disinfectant
  - water_filter
  - water_communal
  - water_truck_liter
  - water_truck_service
  - water_non_potable
  - water_piped
  - water_bottle
  - water_sachet
  - chlorine_liquid
  - chlorine_powder
  - cloth
  - cotton
  - socks
  - bra
  - jeans_trouser
  - underwear_women
  - underwear
  - winter_jacket
  - gumboots
  - half_long_sleeve_t_shirt
  - sweatshirt
  - t_shirt
  - winter_jacket_women
  - winter_jacket_men
  - winter_jacket_children
  - winter_boots_women
  - winter_boots_men
  - sleepsuit_children
  - winter_boots_children
  - winter_boots
  - sweater
  - thermal_children
  - winter_gloves
  - winter_hat
  - winter_socks
  - scarf
  - winter_hat_adult
  - winter_hat_children
  - whistle
