# The msna schems includes all possible sheets for the repeat groups.
# A list of sheet prefixes and sheet_types referenced here is maintained in config/sheet_options.ymal
# if a combination of sheet prefixes and sheet_types is not found in the loaded data
# it will be removed from the schema at run time.

# if adding a new repeat_group the references in config/sheet_options.ymal must also be updated.


_imports:
  - "../../../common/schema_defaults.yaml"

programme_type: msna
output_type: dataset

schema_loaded_sheets:

# main sheets
  - $use: raw_data
    override:
      standard_name: hh_raw_data
      classification: "raw_data_sheet"
      linked_log: hh_deletion_log
      linked_sheet: hh_clean_data

  - $use: clean_data
    override:
      standard_name: hh_clean_data
      classification: "clean_data_sheet"
      linked_log: hh_cleaning_log
      linked_sheet: hh_raw_data

  - $use: cleaning_log_base
    override:
      standard_name: hh_cleaning_log
      parent_sheet: hh_clean_data
      parent_linking_column: uuid
    $append_columns:
      - $use: uuid_column
        override:
          is_unique: false

  - $use: deletion_log_base
    override:
      standard_name: hh_deletion_log
      parent_sheet: hh_raw_data
      parent_linking_column: uuid
    $append_columns:
      - $use: uuid_column

  # roster sheets

  - $use: base_repeat_sheet
    override:
      standard_name: roster_raw_data
      classification: "raw_data_sheet"
      parent_sheet: hh_raw_data
      parent_linking_column: uuid
      linked_log: roster_deletion_log
      linked_sheet: roster_clean_data
    $append_columns:
      - $use: uuid_column
        override:
          standard_name: person_id
          alternate_names: []

  - $use: base_repeat_sheet
    override:
      standard_name: roster_clean_data
      classification: "clean_data_sheet"
      parent_sheet: hh_clean_data
      parent_linking_column: uuid
      linked_log: roster_cleaning_log
      linked_sheet: roster_raw_data
    $append_columns:
      - $use: uuid_column
        override:
          standard_name: person_id
          alternate_names: []

  - $use: cleaning_log_base
    override:
      standard_name: roster_cleaning_log
      parent_sheet: roster_clean_data
      parent_linking_column: person_id
    $append_columns:
      - $use: uuid_column
        override:
          is_unique: false
          standard_name: person_id
          alternate_names: []

  - $use: deletion_log_base
    override:
      standard_name: roster_deletion_log
      parent_sheet: roster_raw_data
      parent_linking_column: person_id
    $append_columns:
      - $use: uuid_column
        override:
          standard_name: person_id
          alternate_names: []
# other repeat groups
  - $use: msna_repeat_group
    variables:
      prefix: edu_

  - $use: msna_repeat_group
    variables:
      prefix: health_

  - $use: msna_repeat_group
    variables:
      prefix: nut_

  - $use: msna_repeat_group
    variables:
      prefix: prot_

  - $use: msna_repeat_group
    variables:
      prefix: preg_

  - $use: msna_repeat_group
    variables:
      prefix: died_member_

  - $use: msna_repeat_group
    variables:
      prefix: adults_working_

  - $use: survey
  - $use: choices
  - $use: variable_tracker_sheet

  
schema_unloaded_sheets:
  - $use: read_me
  - $use: sampling_info  
  - $use: enumerator_performance_sheet
  - $use: checklist_data_cleaning