
_imports:
  - "../../common/schema_defaults.yaml"

dataset_type: "other"

schema_loaded_sheets:
    
  - $use: survey
  - $use: choices
  - $use: deletion_log
  
  - $use: variable_tracker_sheet

schema_unloaded_sheets:
  - $use: read_me
  - $use: sampling_info  

  - $use: enumerator_performance_sheet

