
_imports:
  - "../../../common/schema_defaults.yaml"

dataset_type: "jmmi_analysis"

schema_loaded_sheets:
    
  - $use: survey
  - $use: choices
  - $use: clean_data
    $append_columns:
      - standard_name: "country"
        allow_fuzzy_matching: false
        allow_empty_values: false
      - standard_name: "round"
        allow_fuzzy_matching: false
      - standard_name: "date"
        allow_fuzzy_matching: false
        allow_empty_values: false
      - standard_name: "month"
        allow_fuzzy_matching: false
        allow_empty_values: false
      - standard_name: "year"
        allow_fuzzy_matching: false
        allow_empty_values: false
      - standard_name: "admin1_code"
        allow_fuzzy_matching: false
        allow_empty_values: false
      - standard_name: "admin1_label"
        allow_fuzzy_matching: false
        allow_empty_values: false
      - standard_name: "admin2_code"
        allow_fuzzy_matching: false
        allow_empty_values: false
      - standard_name: "admin2_label" 
        allow_fuzzy_matching: false
        allow_empty_values: false

schema_unloaded_sheets:
  - $use: read_me
  - $use: sampling_info  
  - $use: composite_indicators
  - $use: checklist
