
_imports:
  - "../../../common/schema_defaults.yaml"

programme_type: "other"
output_type: "dataset"

schema_loaded_sheets:
    
  - $use: survey
  - $use: choices
  
  - $use: variable_tracker_sheet

schema_unloaded_sheets:
  - $use: read_me
  - $use: sampling_info  
  - $use: checklist_data_cleaning

  - $use: enumerator_performance_sheet

