name: Publish Release

on:
  repository_dispatch:
    types: [manual-release]

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v6  
        with:
          repository: impact-initiatives/argus_schemas 
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v3
        with:
          tag_name: ${{ github.event.client_payload.release_tag }}
          name:  ${{ github.event.client_payload.release_tag }}
          generate_release_notes: true
